import type { Config } from "tailwindcss";
import {colors as defaultColors} from "tailwindcss/defaultTheme"
const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/Ophelia/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/shared/Components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
      'xxs': '360px',
      'xs': '480px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1200px',
      '2xl': '1340px',
      '3xl': '1536px',
      '4xl': '1680px',
      },
      fontFamily: {
        figtree: ["Figtree"],
      },
      container: {
        center: true,
      },
      colors: { //https://tailwindcss.com/docs/customizing-colors
        deepBlue: "#1e1d6e",
        blueBell: "#4d4bc8",
        lightSlateBlue: "#6b69d1",
        lightSteelBlue: "#8987da",
        lavenderBlue: "#a6a5e3",
        periwinkle: "#c4c3eb",
        periwinkleGray: "#e1e1f5",
        royalBlue: "#3533bb",
        paleSilver: "#f4f4fb",
        electricBlue: "#06f",
        blueZodiac: "#252387",
        blackBean: "#171a20",
        outerSpace: "#2d3341",
        slateGray: "#75819e",
        arctic: "#444d61",
        cadetBlue: "#5b6782",
        manatee: "#959fb5",
        indigo: "#2d2b9f",
        silverChalice: "#b5bccb",
        wildBlueYonder: "#d6dae2",
        blackHaze: "#f6f7f9",
        aliceBlue: "#fbfbfc",
        pomegranate: "#c53a33",
        gainsboro: "#e4e7ec",
        terraCotta: "#d35e4e",
        mediumSeaGreen: "#68c069",
        yellowOrange: "#ffae4f",
        redOrange: "#d12e2a",
        goldTips: "#e39d3e",
        rajah: "#e6672b",
        midnight: "#191f5a",
        dodgerBlue: "#1edffe",
        sandyBrown: "#fd9633",
        heliotrope: "#a96af5",
        silverSand: "#bebddb",
        richElectricBlue: "#1437f5",
        tiaMaria: "#ea3323",
        supernova: "#f6c944",
        eucalyptus: "#88cb8c",
        teaGreen: "#d5f0db",
      },
      spacing: {
        '4.5': '22px',
        '7.5': '30px',
        '12.5': '50px',
        '13': '52px',
        '15': '60px',
        '17.5': '70px',
        '18': '72px',
        '20': '80px',
        '22': '88px',
        '22.5': '90px',
        '25': '100px',
        '30': '120px',
        '35': '140px',
        '37.5': '150px',
        '40': '160px',
        '45': '180px',
        '50': '200px',
        '55': '220px',
        '60': '240px',
        '65': '260px',
        '70': '280px',
        '75': '300px',
      },
      gap: {
        '12': '3rem', 
      },
      flex: {
        "1"	: "1 1 0%",
        "auto"	: "1 1 auto",
        "initial"	: "0 1 auto",
        "none"	: "none",
        "last"	: "0 0 auto",
      },
      animation: {
        'fade': 'fade 1s ease-in-out',
      },
      keyframes: {
        fade: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' }, 
        },
      },
    },
  },
  plugins: [
    require('tailwind-scrollbar')
  ],
};
export default config;
