var inputsTheme: {
    text?: string,
    textarea?: string,
    selectbox?: string,
    filterbox?: string,
    checkbox?: string,
    radio?: string,
    boolean?: string,
    enum?: string,
    password?: string,
    richtext?: string,
    date?: string,
    datetime?: string,
    numeric?: string,
    label?: string,
    file?: string,
    month?: string,
    email?: string,
    phone?: string,
    url?: string,
    range?: string,
    time?: string,
    week?: string
  }
  export type InputsTheme = typeof inputsTheme